# Streamlit theme configuration
[theme]
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#000000"
textColor = "#000000"
base="light"
primaryColor="#f2f2f2"
font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;